# Generated by Django 3.1.7 on 2021-04-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
    ]
