# Generated by Django 3.1.7 on 2021-04-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
    ]
