# Generated by Django 3.1.7 on 2021-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_productreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
