# Generated by Django 3.1.7 on 2021-04-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productreview_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='stars',
        ),
    ]
