# Generated by Django 3.1.7 on 2021-04-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
