# Generated by Django 3.1.7 on 2021-04-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0019_productreview_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(auto_now=True)),
                ('initial_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('price_rent', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
