# Generated by Django 3.1.7 on 2021-04-23 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbook',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentbook',
            name='initial_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
