# Generated by Django 3.1.7 on 2021-04-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_ordermodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
