# Generated by Django 3.1.7 on 2021-04-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_auto_20210427_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='phone',
        ),
    ]
